# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources: 
  repositories:
    - repository: notification
      type: github
      name: maazpatel24/core-templates
      endpoint: maazpatel24

jobs:
  - template: notification/senders.yml@notification
    parameters:
      message: "Hello world Maaz"
      senders:
      - Slack
      - MSTeams
      - OutLook

# ---------------------------------------------

# File: azure-pipelines.yml

# pool:
#   vmImage: 'ubuntu-latest'

# stages:
# - stage: Install
#   jobs: 
#   - job: npminstall
#     steps:
#     - script: echo 'install'
#       displayName: 'Npm'
# - template: templates/stages1.yml # Template reference
# - template: templates/stages2.yml # Template reference
# ------------------------------------------------------------------

# Repo: Contoso/LinuxProduct
# File: azure-pipelines.yml
# resources:
#   repositories:
#     - repository: templates
#       type: github
#       name: RepoTemplates

# jobs:
# - template: BuildTemplates/common.yml@templates  # Template reference
# ----------------------------------------------------------------------

